spring.application.name=mcp-server
spring.ai.mcp.server.protocol=streamable
# sse unidirectionel du serveur au client/ streamable bidirectionel entre client et serveur http2 / stateless
spring.ai.mcp.server.name=mcp-rh
server.port=8989

